#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(NICTA_GPL)
#

libs-$(CONFIG_LIB_SEL4_VMM) += libsel4vmm
libsel4vmm: $(libc) common libpci libsel4 libsel4vka libelf libsel4platsupport libcpio libsel4allocman libsel4vspace libsel4utils libethdrivers libsel4allocman
