#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(DATA61_GPL)
#

libs-$(CONFIG_LIB_SEL4_VMM) += libsel4vmm
libsel4vmm: $(libc) common libpci libsel4 libsel4vka libelf libsel4platsupport libcpio libsel4allocman libsel4vspace libsel4utils libethdrivers libsel4allocman
