#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

libs-$(CONFIG_LIB_SEL4_UTILS) += libsel4utils
libsel4vspace-$(CONFIG_LIB_SEL4_VSPACE) := libsel4vspace
libsel4vka-$(CONFIG_LIB_SEL4_VKA) := libsel4vka
libplatsupport-$(CONFIG_LIB_PLATSUPPORT) := libplatsupport
libsel4platsupport-$(CONFIG_LIB_SEL4_PLAT_SUPPORT) := libsel4platsupport
libsel4simple-$(CONFIG_LIB_SEL4_SIMPLE) := libsel4simple
libsel4utils: $(libsel4vspace-y) $(libsel4vka-y) $(libplatsupport-y) $(libsel4platsupport-y) libutils libelf libcpio libsel4 common $(libc) $(libsel4simple-y)
